### ISSUE TITLE
Live site needs to be updated with latest changes

### ISSUE THREAD

**Issue by timlinux** [AIFDR/inasafe-doc#249]
The live site does not yet reflect the changes made to e.g. governance docs.

Can we please get it updated ASAP

**Comment by mach0** [comment]
done..

**Comment by timlinux** [comment]
@mach0 Yes I think so, thanks.

**Comment by mach0** [comment]
so www.inasafe.org is currently reflecting what's in master and test.inasafe.org is reflecting what's in develop branch .. This should be ok for now.
