### ISSUE TITLE
Update: Governance Pages

### ISSUE THREAD

**Issue by Charlotte-Morgan** [AIFDR/inasafe-doc#252]
Hi @mach0 ,could you please push
http://test.inasafe.org/en/general/governance/roles_and_responsibilities.html 
to 
http://inasafe.org/en/general/governance/roles_and_responsibilities.html

This page is really badly out of date.
I'm pretty sure that i have raised 2 tickets about this before, but i cant find them.
found 1 #249

Thanks 
# cc
@timlinux @MariaSolovyeva

**Comment by mach0** [comment]
sorry for being late .. thought that was already done - but it also seems that stable did not compile anymore and was on a very old version.. done now
