### ISSUE TITLE
Need help for building local documentation

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe-doc#255]
Hi @timlinux and @mach0 

Currently i'm trying to build documentation for my computer to see is there any image that might not show or is there any problem for the table, etc. I'm running dual OS so i follow all of your tutorial in Ubuntu.

Based on your tutorial in front page, i already did this step:

* instal github and clone inasafe-dev and inasafe-doc and put together in $HOME/dev/python
* install all tools that mention in front page

But, when i trying to run this command:
sh ./scripts/post_translate.sh en

I got error like this:
![selection_006](https://cloud.githubusercontent.com/assets/2520159/6592132/042773de-c7fc-11e4-83ed-d2492bd5bef9.png)

And the html or pdf file cannot appear in output folder. Can you explain to me what's wrong with the screenshot i above? Thanks

**Comment by timlinux** [comment]
For the rpl error you can do : 

```sudo apt-get install rpl``

also remove ``sh`` in front of the `` ./scripts/post_translate.sh en`` command.

**Comment by adissadis** [comment]
I already install rpl, but it's still appear that [[: not found and pushd: not found, also there's adition popd: not found
![selection_008](https://cloud.githubusercontent.com/assets/2520159/6594775/b593a0d8-c816-11e4-856d-43fec652e1db.png)

i already removed ``sh`` in front of the ``./scripts/post_translate.sh en`` but it showed that ```permission denied``` when i'm added ``sudo`` in front of the commad, it showed ``command not found``

![selection_009](https://cloud.githubusercontent.com/assets/2520159/6594811/13b4d1d2-c817-11e4-812c-b79cf02b2528.png)

**Comment by mach0** [comment]
hi @adissadis 
which type of shell are you using? because pushd is only available in bash (to my knowledge) - so if you use any other shell than bash it is likely to get that error.
What is the output of 
env | grep SHELL
?

**Comment by adissadis** [comment]
the output from env | grep SHELL is:
``SHELL=/bin/bash``

and i already run the script like
``./scripts/post_translate.sh``
but it still appears that pushd not found.

How to check if my file /bin/bash not a symlink to anyother shell? 

This is the log from shell:
> Compiling messages to i18n/fr/LC_MESSAGES/training/beginner/qgis-inasafe/203-the-basics-of-qgis.mo
35 translated messages, 59 untranslated messages.
Compiling messages to i18n/fr/LC_MESSAGES/training/beginner/qgis-inasafe/211-using-map-composer.mo
1 translated message, 81 untranslated messages.
Compiling messages to i18n/fr/LC_MESSAGES/training/beginner/qgis-inasafe/206-working-with-vector-data.mo
1 translated message, 121 untranslated messages.
Compiling messages to i18n/fr/LC_MESSAGES/training/beginner/qgis-inasafe/210-vector-analysis-for-problem-solving.mo
1 translated message, 137 untranslated messages.
./scripts/post_translate.sh: 90: ./scripts/post_translate.sh: LOCALES+= en: not found
Building HTML for locale 'id'...
/home/sony/dev/python/inasafe-doc/docs/source/general/governance/roles_and_responsibilities.rst:33: WARNING: inconsistent term references in translated message
./scripts/post_translate.sh: 123: ./scripts/post_translate.sh: [[: not found
./scripts/post_translate.sh: 131: ./scripts/post_translate.sh: [[: not found
Replacing "#/../search.html" with "search.html" (case sensitive) (partial words matched)
Replacing "#/../irchat.html" with "irchat.html" (case sensitive) (partial words matched)
./scripts/post_translate.sh: 163: ./scripts/post_translate.sh: pushd: not found
./scripts/post_translate.sh: 182: ./scripts/post_translate.sh: popd: not found
cp: cannot stat ‘resources/en/*’: No such file or directory
cp: cannot stat ‘resources/fr/*’: No such file or directory
cp: cannot stat ‘templates/index-fr.html’: No such file or directory
cp: cannot stat ‘templates/irchat-fr.html’: No such file or directory
Building HTML for locale 'fr'...
Error: Config directory doesn't contain a conf.py file.
./scripts/post_translate.sh: 123: ./scripts/post_translate.sh: [[: not found
./scripts/post_translate.sh: 131: ./scripts/post_translate.sh: [[: not found
rm: cannot remove ‘templates/index.html’: No such file or directory
rm: cannot remove ‘templates/irchat.html’: No such file or directory
rpl: File "./output/html/fr/contents.html" not found.
rpl: File "./output/html/fr/contents.html" not found.
./scripts/post_translate.sh: 163: ./scripts/post_translate.sh: pushd: not found
cp: cannot stat ‘resources/InaSAFE_footer.png’: No such file or directory
./scripts/post_translate.sh: 165: cd: can't cd to build/latex/fr/
./scripts/post_translate.sh: 182: ./scripts/post_translate.sh: popd: not found
>./scripts/post_translate.sh: 188: ./scripts/post_translate.sh: popd: not found

**Comment by mach0** [comment]
which bash
should show you where in your path the executable is: for me its /bin/bash
change into that dir and look what bash is:
cd /bin
ls -alh bash 
should look like: 
-rwxr-xr-x 1 root root 1010K Sep 25 23:48 bash
if it looks like that:
lrwxrwxrwx 1 root root 8 Mar 21  2014 ypdomainname -> hostname
it is a link

And the last idea I have is that you might have an outdated version of bash but that would be so much outdated that I cannot believe it. To test just ask for the version of your bash
bash --version
GNU bash, version 4.3.25(1)-release (x86_64-pc-linux-gnu) <- my version

which linux version are you using?

**Comment by adissadis** [comment]
@mach0 i'm using ubuntu 14.04 64 bit and my bash version is 4.3.11(1)
 
![selection_013](https://cloud.githubusercontent.com/assets/2520159/6661358/a87b2392-cbdd-11e4-871a-ad1d6d4d315c.png)

**Comment by mach0** [comment]
hmm - ok should be recent enough though mine is a bit newer:
macho@lost:~$ bash --version
GNU bash, version 4.3.25(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

Have to create a docker container with 14.04 and take a look. But it really should work.
So you are still missing pushd and popd (and [[ ) commands? That's the only errors left?

**Comment by adissadis** [comment]
I think that's the only error so far.

The output of echo$0 is:
bash

**Comment by mach0** [comment]
slowly I am running out of ideas ..
what happens when you try to use 
popd
pushd
on the command line?

**Comment by adissadis** [comment]
sony@VAIO:~$ popd
bash: popd: directory stack empty
sony@VAIO:~$ pushd
bash: pushd: no other directory

**Comment by timlinux** [comment]
@adissadis lets meet on hipchat and try to get this working interactively.

Regards

Tim

**Comment by adissadis** [comment]
Thanks Tim for helping me solve the problem
