### ISSUE TITLE
Socialisation training - suggested edits to the Overview page

### ISSUE THREAD

**Issue by KathrynOwen** [AIFDR/inasafe-doc#258]
•	Section Input Data>Hazard: 
remove ‘disasters such as’ from the sentence “ Events or phenomena that are seen as hazard potentials include disasters such as earthquakes…” because they are not necessarily disasters. 

![image](https://cloud.githubusercontent.com/assets/10971278/6699259/5ff6f178-cd54-11e4-9818-3b5a62e334bd.png)
 
•	Section Input Data>Hazard: 
remove the ‘s’ at the end of coordinates in the following list for consistency with the list in the exposure section below it and to make it more grammatically correct.

![image](https://cloud.githubusercontent.com/assets/10971278/6699265/676e9596-cd54-11e4-8881-9e623a727d8e.png)

 
•	Section Input Data>Aggregation: 
Is there a better word for aggregation? It isn’t perhaps as intuitive as it could be, especially as the process works to separate, not combine the results… e.g. ‘Classify results by…’?

•	Section Impact Function:
The impact function section is a bit jargon-heavy I found, especially in relation to what exactly an impact function is…. Perhaps include the following sentence (from the ‘Understand Impact Functions page) at the beginning of the section:  ‘An impact function is a software program that computes an impact assessment given a number of inputs.’

•	Section Impact Function>Available Impact Functions:
Should the output for the Tsunami and People row be ‘Number of people affected and number of people needing evacuation’?

![image](https://cloud.githubusercontent.com/assets/10971278/6699271/7bb74aa2-cd54-11e4-8c99-dfc1e9ade364.png)

**Comment by adissadis** [comment]
I have question about impact function, If i include the sentence from Understand Impact Function page, so it will become like this:

> An impact function is a software program that computes an impact assessment given a number of inputs. InaSAFE is capable of having multiple impact functions specific to the input data. Typically an impact function deals with the combination of one hazard layer and one exposure layer. The way the data is combined is specific to the impact function. It could be a simple overlay of the two layers, or it could be a complicated function that calculates if a building would fall down in an earthquake based on building structure information.

**Comment by KathrynOwen** [comment]
That does make a little more sense to me. As someone not knowing what 'Impact Function' meant, i think it is useful to explain what it is in the first sentence.

**Comment by Charlotte-Morgan** [comment]
Hi @KathrynOwen 
Thanks for your feedback & ideas. Its great to get the perspective of a new user the first time they look at the software and training materials. Lots of good points.

Here are some comments on some specific points above:

Aggregation is a good word - lets keep it for now. We are aggregating data by location & summarising by attributes.
Impact Function - I disagree with the edit made above. An Impact Function is not a software program. Maybe its a spatial analysis routine? I note that the whole section about IF will need to be rewritten to align with version 3 and the subsequent IF review. :)

# cc
@adissadis

**Comment by adissadis** [comment]
we need to define the Impact function to simple sentence. Its help people who still new in InaSAFE or who doesn't have geographic background to understand what is the Impact function mean.

**Comment by Charlotte-Morgan** [comment]
I'm closing this ticket because the socialisation materials have been rewritten.
@adissadis - yes we need more description for impact functions - there is another ticket for that
