### ISSUE TITLE
Socialisation training - suggested edits to the Getting Started page

### ISSUE THREAD

**Issue by KathrynOwen** [AIFDR/inasafe-doc#260]
•	Section Set Up QGIS:
I found that although the training materials said that I should be able to find the QGIS shortcut on the desktop and/or Start Menu, it was not in either location on my computer – I had to find it in the Program Files folder on my C drive. Perhaps a note could be included to search the Program Files for users that may experience a similar issue?

•	Section Installing Plugins>InaSAFE:
I found that I had to alter the proxy settings within QGIS before I could access and of the plugins – perhaps a note should be made about this in case other users are in a similar situation?

•	Section Installing Plugins>InaSAFE:
There is no new tab as mentioned in the instructions, in either the image supplied in the training or in the version on my computer.

From the Socialisation training: 
![image](https://cloud.githubusercontent.com/assets/10971278/6701325/913bed54-cd6f-11e4-9af4-80f609c5a846.png)

From my version:
![image](https://cloud.githubusercontent.com/assets/10971278/6701326/995892a8-cd6f-11e4-86df-0015efc7bc31.png)

•	Section Installing Plugins>OpenLayers Plugin:
The instructions don’t match the screenshot included in the training for step 21… i.e. the screenshot directs users to the Web menu which the instructions direct users to the Plugins menu…

![image](https://cloud.githubusercontent.com/assets/10971278/6701331/a4cf7642-cd6f-11e4-88c5-aa68115d5b50.png)

**Comment by Charlotte-Morgan** [comment]
thank @KathrynOwen 

some comments may be specific to GA operating environment & not relevant to most users. @adissadis can you please look over this and update as required?

**Comment by adissadis** [comment]
Okay Charlote, I already looked it and made several changes according to it.
