### ISSUE TITLE
HOT Team will update material for InaSAFE website

### ISSUE THREAD

**Issue by adissadis** [AIFDR/inasafe-doc#283]
Currently training material in InaSAFE website are:

* InaSAFE socialization material
* Beginner OSM
* Beginner QGIS and InaSAFE
* Intermediate OSM
* Intermediate QGIS and InaSAFE

we want to update all to training materials so it only contains:

* InaSAFE socialization material (new)
* OSM training
* QGIS and InaSAFE training for disaster management

We need to figure out how to archive the old training materials. Maybe @timlinux can help us to archive the old training materials?

Thanks

**Comment by timlinux** [comment]
Hi

Are the old materials all in GIT? I suggest to tag them before revising them.

Regards

Tim

**Comment by Charlotte-Morgan** [comment]
hi @adissadis - further to our emails (and thanks for opening a ticket here) do you think you need to wait until you have seen 3.2 and updated the docs before you load them or will you make more changes once they are loaded and before the new web site is live?

**Comment by adissadis** [comment]
Hi @timlinux yes the old material all in GIT. How to tag them? Should i create a folder in resource or source named "archive" or what?

@Charlotte-Morgan we already pull InaSAFE 3.2 from Github and we will use it and make changes if there're some change/tweaks while feature freeze happen

**Comment by timlinux** [comment]
Hi Adiityo

> On 24 Aug 2015, at 05:09, Adityo Dwijananto <notifications@github.com> wrote:
> 
> Hi @timlinux <https://github.com/timlinux> yes the old material all in GIT. How to tag them? Should i create a folder in resource or source named "archive" or what?
> 

You can check out the revision that contained that version and then use git tag to create the tag, then push that tag to the main repo in github. You can see the general workflow I follow when releasing InaSAFE to take inspiration from here:

https://github.com/AIFDR/inasafe/wiki/Preparing-a-release#tag-the-release <https://github.com/AIFDR/inasafe/wiki/Preparing-a-release#tag-the-release>

Regards

Tim

> @Charlotte-Morgan <https://github.com/Charlotte-Morgan> we already pull InaSAFE 3.2 from Github and we will use it and make changes if there're some change/tweaks while feature freeze happen
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/AIFDR/inasafe-doc/issues/283#issuecomment-134002090>.
> 

—





Tim Sutton

Visit http://kartoza.com <http://kartoza.com/> to find out about open source:

* Desktop GIS programming services
* Geospatial web development
* GIS Training
* Consulting Services

Skype: timlinux Irc: timlinux on #qgis at freenode.net
Tim is a member of the QGIS Project Steering Committee

Kartoza is a merger between Linfiniti and Afrispatial

**Comment by timlinux** [comment]
@adissadis - can we close this of - or can you give a status update?

**Comment by adissadis** [comment]
@timlinux yes you can close it. It's already in website now.


Next step is we waiting the transifex to translate into bahasa indonesia.

I will create another separate issue about this
